### ISSUE TITLE
Webex Stuck at Lobby

### ISSUE THREAD

**Issue by RustyWar** [APet99/ZoomWebExAutoJoiner#2]
Hello thank you for this wonderful program. I stubbled upon a problem where when the program opens the link and starts webex it will not join the meeting but will be stuck at the lobby where the user has to press "Join Meeting" to enter the meeting. 
![image](https://user-images.githubusercontent.com/17228028/111817077-86e05000-8918-11eb-833e-50205a7fd4b4.png)

This is my first time using python and honestly I have no idea how to fix it until I realized that If you press space at the lobby , you will enter the meeting. So I added some code that I googled and was truly amazed it worked. These are the modifications done

![image](https://user-images.githubusercontent.com/17228028/111817037-792aca80-8918-11eb-936a-fddc937bbcd5.png)

I just literally spammed space key and it worked. First time using python and was able to fix this haha.  Oh this is also my first post .

**Comment by APet99** [comment]
Hi @RustyWar,
Thank you for the feedback. If I understand the issue correctly, WebEx launches, but does not join the room, and pressing space multiple times would join the room?

Thank you for including screenshots and your workaround. I will take a look and see what can be done to remove this issue altogether. Please don't hesitate to post if any other issues that come up.

**Comment by RustyWar** [comment]
> Hi @RustyWar,
> Thank you for the feedback. If I understand the issue correctly, WebEx launches, but does not join the room, and pressing space multiple times would join the room?
> 
> Thank you for including screenshots and your workaround. I will take a look and see what can be done to remove this issue altogether. Please don't hesitate to post if any other issues that come up.

Yes you are correct.  You're welcome!

**Comment by APet99** [comment]
I wanted to follow up and say the issue *should* be fixed now.

If you get the newest version, it should work much better. If it still does not work, or you find more issues, feel free to let me know.
