### ISSUE TITLE
Custom message not working

### ISSUE THREAD

**Issue by Narcissus00** [APet99/ZoomWebExAutoJoiner#3]
Testing it out, I couldn't get the custom message to work.  The log says that it isn't able to find the chat button. I have pasted the logs below

2021-04-17	05:02:10		Looked for: images\ZOOM\chat_light.png
2021-04-17	05:02:10		Looked for: images\ZOOM\chat_dark.png
2021-04-17	05:02:10		Moved Mouse Cursor To None
2021-04-17	05:02:10		Took Screenshot of session x
2021-04-17	05:02:10		No End Time Specified. You must exit the meeting manually.

I may be just being stupid

**Comment by APet99** [comment]
Hey @Narcissus00 

Thank you for letting me know. I will take a look and see what is going on. 

I got a few questions:
- Are you on a Windows or Mac?
- Is your Zoom theme light or dark mode?

**Comment by Narcissus00** [comment]
Thank you for so quickly getting back to me. I am on Windows, and regarding the theme I have looked everywhere but I just cannot seem to find the option to change my theme. It is not where it's supposed to be according to the internet. I have even installed the latest version of Zoom from their website
![Capture](https://user-images.githubusercontent.com/70282971/115096187-864dd000-9f3d-11eb-9359-f42da3556455.PNG)

The chat icon does, however, look like chat_dark image in the folder
![Capture2](https://user-images.githubusercontent.com/70282971/115096262-cc0a9880-9f3d-11eb-8ea8-4f439c11d682.PNG)

EDIT: Oh, there's no themes on Windows, apparently.

**Comment by APet99** [comment]
Gotcha. It looks like the chat image is not being recognized (I have a good idea why). I will try to fix it shortly. I'll ping you when the update is made so you can pull the fix.

If the issue continues to occur, don't hesitate to let me know.

-Alex

**Comment by Narcissus00** [comment]
Thank you, Alex. Great program

- Mazen

**Comment by APet99** [comment]
I believe it *should* be working now. If you are still experiencing an issue, let me know. 
You can pull the changes to get the most up-to-date version.

Let me know if it works, so the issue can be resolved.


If you enjoy the project, make sure to star it :)

-Alex

**Comment by Narcissus00** [comment]
It works now, great! I did, however, have to change Zoom settings to start the meetings in full screen to get it to work. Otherwise it would just minimize the window of Zoom.
