### ISSUE TITLE
Facing issue while running the docker in Windows

### ISSUE THREAD

**Issue by KananVyas** [APet99/ZoomWebExAutoJoiner#7]
Hi, I faced this issue while running on Windows10 Powershell. [](url)
![error](https://user-images.githubusercontent.com/20103336/121976872-55094900-cda2-11eb-8b86-c5a49d19e58c.PNG)

**Comment by APet99** [comment]
Hello!

Thank you for sharing the issue you ran into. Are you attempting to run on a windows container or Linux? The script is currently not supported on Linux, but will be fixed soon.
